### ISSUE TITLE
Certain tests get stuck in the ABORTING status until controller is rebooted

### ISSUE THREAD

**Issue by dcransac** [denkbar/step#3]
- Seems like a race condition type thing
- Factors for problem occurence unclear and problem not actively reproduceable
- We'll use this issue to gather data until we figure out where the problem comes from

-> Any softer workaround ideas to un-stuck the test (i.e without rebooting the controller which is kind of brutal)?

**Comment by jeromecomte** [comment]
The issue could be reproduced. 

It occurs when a thread running a query in MongoDB is suddenly interrupted by the ThreadManager. 

When a test is aborted the ThreadManager collects a list of all the Threads that can be safely interrupted. The interruption itself occurs a few ms later based on that list. Because the threads continue to run during this short interval it can happen that the ThreadManager interrupts a Thread that cannot be interrupted safely.

As a quickfix I suggest to disable the ThreadManager. If we still want to use the ThreadManager in the future we should rewrite the selection logic of the ThreadManager

**Comment by dcransac** [comment]
But that means users wouldn't be able abort tests anymore, correct?

**Comment by jeromecomte** [comment]
They would. But sleeps/quotas waits/token selections won't be interrupted anymore

**Comment by dcransac** [comment]
Sounds good then.

**Comment by dcransac** [comment]
Considered to be fixed.
